#include "SL.h"
SL singlelepton;
namespace sl {
	const float &evt_pfmet() { return singlelepton.evt_pfmet(); }
	const float &evt_pfmetPhi() { return singlelepton.evt_pfmetPhi(); }
	const float &evt_trackmet() { return singlelepton.evt_trackmet(); }
	const float &evt_trackmetPhi() { return singlelepton.evt_trackmetPhi(); }
	const float &evt_met3p0() { return singlelepton.evt_met3p0(); }
	const float &evt_met3p0Phi() { return singlelepton.evt_met3p0Phi(); }
	const float &evt_pfsumet() { return singlelepton.evt_pfsumet(); }
	const float &evt_pfmetSig() { return singlelepton.evt_pfmetSig(); }
	const int &evt_event() { return singlelepton.evt_event(); }
	const int &evt_lumiBlock() { return singlelepton.evt_lumiBlock(); }
	const int &evt_run() { return singlelepton.evt_run(); }
	const bool &filt_csc() { return singlelepton.filt_csc(); }
	const bool &filt_hbhe() { return singlelepton.filt_hbhe(); }
	const bool &passes_met_filters() { return singlelepton.passes_met_filters(); }
	const bool &filt_hcallaser() { return singlelepton.filt_hcallaser(); }
	const bool &filt_ecaltp() { return singlelepton.filt_ecaltp(); }
	const bool &filt_trkfail() { return singlelepton.filt_trkfail(); }
	const bool &filt_eebadsc() { return singlelepton.filt_eebadsc(); }
	const bool &evt_isRealData() { return singlelepton.evt_isRealData(); }
	const float &scale1fb() { return singlelepton.scale1fb(); }
	const float &evt_xsec_incl() { return singlelepton.evt_xsec_incl(); }
	const float &evt_kfactor() { return singlelepton.evt_kfactor(); }
	const float &gen_met() { return singlelepton.gen_met(); }
	const float &gen_metPhi() { return singlelepton.gen_metPhi(); }
	const float &njets() { return singlelepton.njets(); }
	const float &ht() { return singlelepton.ht(); }
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &jets() { return singlelepton.jets(); }
	const vector<float> &jets_disc() { return singlelepton.jets_disc(); }
	const TString &sample() { return singlelepton.sample(); }
	const int &nFOs_SS() { return singlelepton.nFOs_SS(); }
	const int &nvtx() { return singlelepton.nvtx(); }
	const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &p4() { return singlelepton.p4(); }
	const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &tag_p4() { return singlelepton.tag_p4(); }
	const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &dilep_p4() { return singlelepton.dilep_p4(); }
	const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &mc_p4() { return singlelepton.mc_p4(); }
	const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &mc_motherp4() { return singlelepton.mc_motherp4(); }
	const int &mc_motherid() { return singlelepton.mc_motherid(); }
	const int &id() { return singlelepton.id(); }
	const bool &isPF() { return singlelepton.isPF(); }
	const int &idx() { return singlelepton.idx(); }
	const float &dxyPV() { return singlelepton.dxyPV(); }
	const float &dZ() { return singlelepton.dZ(); }
	const float &dxyPV_err() { return singlelepton.dxyPV_err(); }
	const int &motherID() { return singlelepton.motherID(); }
	const int &mc_id() { return singlelepton.mc_id(); }
	const float &RelIso03() { return singlelepton.RelIso03(); }
	const float &RelIso03EA() { return singlelepton.RelIso03EA(); }
	const float &RelIso03DB() { return singlelepton.RelIso03DB(); }
	const float &pfChargedHadronIso() { return singlelepton.pfChargedHadronIso(); }
	const float &pfPhotonIso() { return singlelepton.pfPhotonIso(); }
	const float &pfNeutralHadronIso() { return singlelepton.pfNeutralHadronIso(); }
	const float &tkIso() { return singlelepton.tkIso(); }
	const float &sumPUPt() { return singlelepton.sumPUPt(); }
	const bool &passes_SS_tight_v3() { return singlelepton.passes_SS_tight_v3(); }
	const bool &passes_SS_tight_noiso_v3() { return singlelepton.passes_SS_tight_noiso_v3(); }
	const bool &passes_SS_fo_v3() { return singlelepton.passes_SS_fo_v3(); }
	const bool &passes_SS_fo_noiso_v3() { return singlelepton.passes_SS_fo_noiso_v3(); }
	const bool &passes_SS_fo_looseMVA_v3() { return singlelepton.passes_SS_fo_looseMVA_v3(); }
	const bool &passes_SS_fo_looseMVA_noiso_v3() { return singlelepton.passes_SS_fo_looseMVA_noiso_v3(); }
	const bool &passes_WW_medium_v1() { return singlelepton.passes_WW_medium_v1(); }
	const bool &passes_WW_medium_noiso_v1() { return singlelepton.passes_WW_medium_noiso_v1(); }
	const bool &passes_WW_fo_v1() { return singlelepton.passes_WW_fo_v1(); }
	const bool &passes_WW_fo_noiso_v1() { return singlelepton.passes_WW_fo_noiso_v1(); }
	const bool &passes_WW_fo_looseMVA_v1() { return singlelepton.passes_WW_fo_looseMVA_v1(); }
	const bool &passes_WW_fo_looseMVA_noiso_v1() { return singlelepton.passes_WW_fo_looseMVA_noiso_v1(); }
	const bool &passes_WW_veto_v1() { return singlelepton.passes_WW_veto_v1(); }
	const bool &passes_WW_veto_noiso_v1() { return singlelepton.passes_WW_veto_noiso_v1(); }
	const bool &passes_HAD_veto_v3() { return singlelepton.passes_HAD_veto_v3(); }
	const bool &passes_HAD_veto_noiso_v3() { return singlelepton.passes_HAD_veto_noiso_v3(); }
	const bool &passes_HAD_loose_v3() { return singlelepton.passes_HAD_loose_v3(); }
	const bool &passes_HAD_loose_noiso_v3() { return singlelepton.passes_HAD_loose_noiso_v3(); }
	const bool &passes_POG_vetoID() { return singlelepton.passes_POG_vetoID(); }
	const bool &passes_POG_looseID() { return singlelepton.passes_POG_looseID(); }
	const bool &passes_POG_mediumID() { return singlelepton.passes_POG_mediumID(); }
	const bool &passes_POG_tightID() { return singlelepton.passes_POG_tightID(); }
	const float &ip3d() { return singlelepton.ip3d(); }
	const float &ip3derr() { return singlelepton.ip3derr(); }
	const int &type() { return singlelepton.type(); }
	const float &mt() { return singlelepton.mt(); }
	const float &ptrelv0() { return singlelepton.ptrelv0(); }
	const float &ptrelv1() { return singlelepton.ptrelv1(); }
	const float &miniiso() { return singlelepton.miniiso(); }
	const float &miniisoDB() { return singlelepton.miniisoDB(); }
	const float &reliso04() { return singlelepton.reliso04(); }
	const float &annulus04() { return singlelepton.annulus04(); }
	const float &iso03sumPt() { return singlelepton.iso03sumPt(); }
	const float &iso03emEt() { return singlelepton.iso03emEt(); }
	const float &iso03hadEt() { return singlelepton.iso03hadEt(); }
	const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &jet_close_lep() { return singlelepton.jet_close_lep(); }
	const float &ptratio() { return singlelepton.ptratio(); }
	const int &tag_charge() { return singlelepton.tag_charge(); }
	const float &tag_eSeed() { return singlelepton.tag_eSeed(); }
	const float &tag_eSCraw() { return singlelepton.tag_eSCraw(); }
	const bool &tag_HLTLeadingLeg() { return singlelepton.tag_HLTLeadingLeg(); }
	const int &tag_HLT_Ele25WP60_Ele8_Mass55_LeadingLeg() { return singlelepton.tag_HLT_Ele25WP60_Ele8_Mass55_LeadingLeg(); }
	const int &tag_HLT_Ele25WP60_SC4_Mass55_LeadingLeg() { return singlelepton.tag_HLT_Ele25WP60_SC4_Mass55_LeadingLeg(); }
	const int &tag_HLT_Ele33_CaloIdL_TrackIdL_IsoVL_PFJet30_ElectronLeg() { return singlelepton.tag_HLT_Ele33_CaloIdL_TrackIdL_IsoVL_PFJet30_ElectronLeg(); }
	const int &tag_HLT_Ele23_CaloIdL_TrackIdL_IsoVL_PFJet30_ElectronLeg() { return singlelepton.tag_HLT_Ele23_CaloIdL_TrackIdL_IsoVL_PFJet30_ElectronLeg(); }
	const int &tag_HLT_Ele18_CaloIdL_TrackIdL_IsoVL_PFJet30_ElectronLeg() { return singlelepton.tag_HLT_Ele18_CaloIdL_TrackIdL_IsoVL_PFJet30_ElectronLeg(); }
	const int &tag_HLT_Ele12_CaloIdL_TrackIdL_IsoVL_PFJet30_ElectronLeg() { return singlelepton.tag_HLT_Ele12_CaloIdL_TrackIdL_IsoVL_PFJet30_ElectronLeg(); }
	const int &tag_HLT_Ele33_CaloIdM_TrackIdM_PFJet30_ElectronLeg() { return singlelepton.tag_HLT_Ele33_CaloIdM_TrackIdM_PFJet30_ElectronLeg(); }
	const int &tag_HLT_Ele23_CaloIdM_TrackIdM_PFJet30_ElectronLeg() { return singlelepton.tag_HLT_Ele23_CaloIdM_TrackIdM_PFJet30_ElectronLeg(); }
	const int &tag_HLT_Ele18_CaloIdM_TrackIdM_PFJet30_ElectronLeg() { return singlelepton.tag_HLT_Ele18_CaloIdM_TrackIdM_PFJet30_ElectronLeg(); }
	const int &tag_HLT_Ele12_CaloIdM_TrackIdM_PFJet30_ElectronLeg() { return singlelepton.tag_HLT_Ele12_CaloIdM_TrackIdM_PFJet30_ElectronLeg(); }
	const int &tag_HLT_Ele8_CaloIdM_TrackIdM_PFJet30_ElectronLeg() { return singlelepton.tag_HLT_Ele8_CaloIdM_TrackIdM_PFJet30_ElectronLeg(); }
	const int &tag_HLT_Ele27_eta2p1_WP75_Gsf() { return singlelepton.tag_HLT_Ele27_eta2p1_WP75_Gsf(); }
	const int &tag_HLT_Ele27_WP85_Gsf() { return singlelepton.tag_HLT_Ele27_WP85_Gsf(); }
	const int &tag_HLT_Ele27_eta2p1_WPLoose_Gsf() { return singlelepton.tag_HLT_Ele27_eta2p1_WPLoose_Gsf(); }
	const int &tag_HLT_Ele27_eta2p1_WPTight_Gsf() { return singlelepton.tag_HLT_Ele27_eta2p1_WPTight_Gsf(); }
	const int &tag_HLT_Ele32_eta2p1_WP75_Gsf() { return singlelepton.tag_HLT_Ele32_eta2p1_WP75_Gsf(); }
	const int &tag_HLT_Ele32_eta2p1_WPLoose_Gsf() { return singlelepton.tag_HLT_Ele32_eta2p1_WPLoose_Gsf(); }
	const int &tag_HLT_Ele32_eta2p1_WPTight_Gsf() { return singlelepton.tag_HLT_Ele32_eta2p1_WPTight_Gsf(); }
	const int &tag_HLT_Ele22_eta2p1_WPLoose_Gsf() { return singlelepton.tag_HLT_Ele22_eta2p1_WPLoose_Gsf(); }
	const int &tag_HLT_Ele22_eta2p1_WPTight_Gsf() { return singlelepton.tag_HLT_Ele22_eta2p1_WPTight_Gsf(); }
	const int &tag_HLT_Ele23_WPLoose_Gsf() { return singlelepton.tag_HLT_Ele23_WPLoose_Gsf(); }
	const int &tag_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_LeadingLeg() { return singlelepton.tag_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_LeadingLeg(); }
	const int &tag_HLT_Ele23_CaloIdL_TrackIdL_IsoVL() { return singlelepton.tag_HLT_Ele23_CaloIdL_TrackIdL_IsoVL(); }
	const int &tag_HLT_Ele12_CaloIdL_TrackIdL_IsoVL() { return singlelepton.tag_HLT_Ele12_CaloIdL_TrackIdL_IsoVL(); }
	const int &probe_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_LeadingLeg() { return singlelepton.probe_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_LeadingLeg(); }
	const int &probe_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_TrailingLeg() { return singlelepton.probe_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_TrailingLeg(); }
	const int &tag_HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ_TrailingLeg() { return singlelepton.tag_HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ_TrailingLeg(); }
	const int &tag_HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ_LeadingLeg() { return singlelepton.tag_HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ_LeadingLeg(); }
	const int &tag_HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_TrailingLeg() { return singlelepton.tag_HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_TrailingLeg(); }
	const int &tag_HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_LeadingLeg() { return singlelepton.tag_HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_LeadingLeg(); }
	const int &tag_HLT_IsoMu20() { return singlelepton.tag_HLT_IsoMu20(); }
	const int &tag_HLT_IsoTkMu20() { return singlelepton.tag_HLT_IsoTkMu20(); }
	const int &tag_HLT_IsoMu24_eta2p1() { return singlelepton.tag_HLT_IsoMu24_eta2p1(); }
	const int &tag_HLT_IsoTkMu24_eta2p1() { return singlelepton.tag_HLT_IsoTkMu24_eta2p1(); }
	const int &tag_HLT_IsoMu27() { return singlelepton.tag_HLT_IsoMu27(); }
	const int &tag_HLT_IsoTkMu27() { return singlelepton.tag_HLT_IsoTkMu27(); }
	const int &tag_HLT_Mu8_TrkIsoVVL() { return singlelepton.tag_HLT_Mu8_TrkIsoVVL(); }
	const int &tag_HLT_Mu17_TrkIsoVVL() { return singlelepton.tag_HLT_Mu17_TrkIsoVVL(); }
	const int &tag_HLT_Mu8() { return singlelepton.tag_HLT_Mu8(); }
	const int &tag_HLT_Mu17() { return singlelepton.tag_HLT_Mu17(); }
	const int &probe_HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ_TrailingLeg() { return singlelepton.probe_HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ_TrailingLeg(); }
	const int &probe_HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ_LeadingLeg() { return singlelepton.probe_HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ_LeadingLeg(); }
	const int &probe_HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_TrailingLeg() { return singlelepton.probe_HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_TrailingLeg(); }
	const int &probe_HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_LeadingLeg() { return singlelepton.probe_HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_LeadingLeg(); }
	const float &dilep_mass() { return singlelepton.dilep_mass(); }
	const bool &isRandom() { return singlelepton.isRandom(); }
	const float &sigmaIEtaIEta_full5x5() { return singlelepton.sigmaIEtaIEta_full5x5(); }
	const float &sigmaIEtaIEta() { return singlelepton.sigmaIEtaIEta(); }
	const float &etaSC() { return singlelepton.etaSC(); }
	const float &dEtaIn() { return singlelepton.dEtaIn(); }
	const float &dPhiIn() { return singlelepton.dPhiIn(); }
	const float &hOverE() { return singlelepton.hOverE(); }
	const float &eSeed() { return singlelepton.eSeed(); }
	const float &ecalEnergy() { return singlelepton.ecalEnergy(); }
	const float &eOverPIn() { return singlelepton.eOverPIn(); }
	const bool &conv_vtx_flag() { return singlelepton.conv_vtx_flag(); }
	const int &exp_innerlayers() { return singlelepton.exp_innerlayers(); }
	const int &charge() { return singlelepton.charge(); }
	const int &sccharge() { return singlelepton.sccharge(); }
	const int &ckf_charge() { return singlelepton.ckf_charge(); }
	const bool &threeChargeAgree() { return singlelepton.threeChargeAgree(); }
	const float &mva() { return singlelepton.mva(); }
	const float &ecalIso() { return singlelepton.ecalIso(); }
	const float &hcalIso() { return singlelepton.hcalIso(); }
	const float &ecalPFClusterIso() { return singlelepton.ecalPFClusterIso(); }
	const float &hcalPFClusterIso() { return singlelepton.hcalPFClusterIso(); }
	const int &ckf_laywithmeas() { return singlelepton.ckf_laywithmeas(); }
	const float &sigmaIPhiIPhi_full5x5() { return singlelepton.sigmaIPhiIPhi_full5x5(); }
	const float &e1x5_full5x5() { return singlelepton.e1x5_full5x5(); }
	const float &e5x5_full5x5() { return singlelepton.e5x5_full5x5(); }
	const float &r9_full5x5() { return singlelepton.r9_full5x5(); }
	const float &etaSCwidth() { return singlelepton.etaSCwidth(); }
	const float &phiSCwidth() { return singlelepton.phiSCwidth(); }
	const float &eSCRaw() { return singlelepton.eSCRaw(); }
	const float &eSCPresh() { return singlelepton.eSCPresh(); }
	const float &ckf_chi2() { return singlelepton.ckf_chi2(); }
	const int &ckf_ndof() { return singlelepton.ckf_ndof(); }
	const float &chi2() { return singlelepton.chi2(); }
	const int &ndof() { return singlelepton.ndof(); }
	const float &fbrem() { return singlelepton.fbrem(); }
	const float &eOverPOut() { return singlelepton.eOverPOut(); }
	const float &dEtaOut() { return singlelepton.dEtaOut(); }
	const float &dPhiOut() { return singlelepton.dPhiOut(); }
	const int &pid_PFMuon() { return singlelepton.pid_PFMuon(); }
	const float &gfit_chi2() { return singlelepton.gfit_chi2(); }
	const float &gfit_ndof() { return singlelepton.gfit_ndof(); }
	const int &gfit_validSTAHits() { return singlelepton.gfit_validSTAHits(); }
	const int &numberOfMatchedStations() { return singlelepton.numberOfMatchedStations(); }
	const int &validPixelHits() { return singlelepton.validPixelHits(); }
	const int &nlayers() { return singlelepton.nlayers(); }
	const float &chi2LocalPosition() { return singlelepton.chi2LocalPosition(); }
	const float &trkKink() { return singlelepton.trkKink(); }
	const int &validHits() { return singlelepton.validHits(); }
	const int &lostHits() { return singlelepton.lostHits(); }
	const int &exp_outerlayers() { return singlelepton.exp_outerlayers(); }
	const float &segmCompatibility() { return singlelepton.segmCompatibility(); }
	const int &HLT_Mu8_TrkIsoVVL() { return singlelepton.HLT_Mu8_TrkIsoVVL(); }
	const int &HLT_Mu17_TrkIsoVVL() { return singlelepton.HLT_Mu17_TrkIsoVVL(); }
	const int &HLT_Mu24_TrkIsoVVL() { return singlelepton.HLT_Mu24_TrkIsoVVL(); }
	const int &HLT_Mu34_TrkIsoVVL() { return singlelepton.HLT_Mu34_TrkIsoVVL(); }
	const int &HLT_Mu8() { return singlelepton.HLT_Mu8(); }
	const int &HLT_Mu17() { return singlelepton.HLT_Mu17(); }
	const int &HLT_Mu24() { return singlelepton.HLT_Mu24(); }
	const int &HLT_Mu34() { return singlelepton.HLT_Mu34(); }
	const int &HLT_Mu10_CentralPFJet30_BTagCSV0p5PF() { return singlelepton.HLT_Mu10_CentralPFJet30_BTagCSV0p5PF(); }
	const int &HLT_IsoMu20() { return singlelepton.HLT_IsoMu20(); }
	const int &HLT_IsoTkMu20() { return singlelepton.HLT_IsoTkMu20(); }
	const int &HLT_Mu10_CentralPFJet30_BTagCSV0p54PF() { return singlelepton.HLT_Mu10_CentralPFJet30_BTagCSV0p54PF(); }
	const int &HLT_IsoMu24_eta2p1() { return singlelepton.HLT_IsoMu24_eta2p1(); }
	const int &HLT_IsoTkMu24_eta2p1() { return singlelepton.HLT_IsoTkMu24_eta2p1(); }
	const int &HLT_IsoMu27() { return singlelepton.HLT_IsoMu27(); }
	const int &HLT_IsoTkMu27() { return singlelepton.HLT_IsoTkMu27(); }
	const int &HLT_Mu45_eta2p1() { return singlelepton.HLT_Mu45_eta2p1(); }
	const int &HLT_Mu50() { return singlelepton.HLT_Mu50(); }
	const int &HLT_Ele8_CaloIdM_TrackIdM_PFJet30() { return singlelepton.HLT_Ele8_CaloIdM_TrackIdM_PFJet30(); }
	const int &HLT_Ele12_CaloIdM_TrackIdM_PFJet30() { return singlelepton.HLT_Ele12_CaloIdM_TrackIdM_PFJet30(); }
	const int &HLT_Ele18_CaloIdM_TrackIdM_PFJet30() { return singlelepton.HLT_Ele18_CaloIdM_TrackIdM_PFJet30(); }
	const int &HLT_Ele23_CaloIdM_TrackIdM_PFJet30() { return singlelepton.HLT_Ele23_CaloIdM_TrackIdM_PFJet30(); }
	const int &HLT_Ele33_CaloIdM_TrackIdM_PFJet30() { return singlelepton.HLT_Ele33_CaloIdM_TrackIdM_PFJet30(); }
	const int &HLT_Ele12_CaloIdL_TrackIdL_IsoVL_PFJet30() { return singlelepton.HLT_Ele12_CaloIdL_TrackIdL_IsoVL_PFJet30(); }
	const int &HLT_Ele18_CaloIdL_TrackIdL_IsoVL_PFJet30() { return singlelepton.HLT_Ele18_CaloIdL_TrackIdL_IsoVL_PFJet30(); }
	const int &HLT_Ele23_CaloIdL_TrackIdL_IsoVL_PFJet30() { return singlelepton.HLT_Ele23_CaloIdL_TrackIdL_IsoVL_PFJet30(); }
	const int &HLT_Ele33_CaloIdL_TrackIdL_IsoVL_PFJet30() { return singlelepton.HLT_Ele33_CaloIdL_TrackIdL_IsoVL_PFJet30(); }
	const int &HLT_Ele10_CaloIdM_TrackIdM_CentralPFJet30_BTagCSV0p5PF() { return singlelepton.HLT_Ele10_CaloIdM_TrackIdM_CentralPFJet30_BTagCSV0p5PF(); }
	const int &HLT_Ele10_CaloIdM_TrackIdM_CentralPFJet30_BTagCSV0p54PF() { return singlelepton.HLT_Ele10_CaloIdM_TrackIdM_CentralPFJet30_BTagCSV0p54PF(); }
	const int &HLT_Ele27_eta2p1_WP75_Gsf() { return singlelepton.HLT_Ele27_eta2p1_WP75_Gsf(); }
	const int &HLT_Ele27_WP85_Gsf() { return singlelepton.HLT_Ele27_WP85_Gsf(); }
	const int &HLT_Ele27_eta2p1_WPLoose_Gsf() { return singlelepton.HLT_Ele27_eta2p1_WPLoose_Gsf(); }
	const int &HLT_Ele27_eta2p1_WPTight_Gsf() { return singlelepton.HLT_Ele27_eta2p1_WPTight_Gsf(); }
	const int &HLT_Ele32_eta2p1_WP75_Gsf() { return singlelepton.HLT_Ele32_eta2p1_WP75_Gsf(); }
	const int &HLT_Ele32_eta2p1_WPLoose_Gsf() { return singlelepton.HLT_Ele32_eta2p1_WPLoose_Gsf(); }
	const int &HLT_Ele32_eta2p1_WPTight_Gsf() { return singlelepton.HLT_Ele32_eta2p1_WPTight_Gsf(); }
	const int &HLT_Ele22_eta2p1_WPLoose_Gsf() { return singlelepton.HLT_Ele22_eta2p1_WPLoose_Gsf(); }
	const int &HLT_Ele22_eta2p1_WPTight_Gsf() { return singlelepton.HLT_Ele22_eta2p1_WPTight_Gsf(); }
	const int &HLT_Ele23_WPLoose_Gsf() { return singlelepton.HLT_Ele23_WPLoose_Gsf(); }
	const int &HLT_Ele23_CaloIdL_TrackIdL_IsoVL() { return singlelepton.HLT_Ele23_CaloIdL_TrackIdL_IsoVL(); }
	const int &HLT_Ele12_CaloIdL_TrackIdL_IsoVL() { return singlelepton.HLT_Ele12_CaloIdL_TrackIdL_IsoVL(); }
	const int &HLT_Mu8_Ele8_CaloIdM_TrackIdM_Mass8_PFHT300() { return singlelepton.HLT_Mu8_Ele8_CaloIdM_TrackIdM_Mass8_PFHT300(); }
	const int &HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL() { return singlelepton.HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL(); }
	const int &HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL() { return singlelepton.HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL(); }
	const int &HLT_DoubleMu8_Mass8_PFHT300() { return singlelepton.HLT_DoubleMu8_Mass8_PFHT300(); }
	const int &HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL() { return singlelepton.HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL(); }
	const int &HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL() { return singlelepton.HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL(); }
	const int &HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ() { return singlelepton.HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ(); }
	const int &HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ() { return singlelepton.HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ(); }
	const int &HLT_DoubleEle8_CaloIdM_TrackIdM_Mass8_PFHT300() { return singlelepton.HLT_DoubleEle8_CaloIdM_TrackIdM_Mass8_PFHT300(); }
	const int &HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ() { return singlelepton.HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ(); }
	const int &HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL() { return singlelepton.HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL(); }
}
